### PR TITLE
FIX Make the carousel dynamic #15

### PR DESCRIPTION
**Pull request by navidzand131**
schema of mock api:
```
{
      id: 1,
      url: "URL", 
      alt: "image's alt text"
}
```

## Changes
* svelte added to project
* ImageRoll component changed

before load:
image

after load:
image

### CODE REVIEW

**Comment by armantorkzaban** [comment]
This is wonderful, Navid. Also welcome on board with your first commit.

**Comment by desputinski** [comment]
Great! Maybe also add student protests, and climate protests:
something from here
https://de.wikipedia.org/wiki/Studentenprotest
And this: https://de.wikipedia.org/wiki/Letzte_Generation#/media/Datei:Der_Aufstand_der_Letzten_Generation_blockiert_Stra%C3%9Fe_am_Hauptbahnhof_(51848563018).jpg

?

These images should have an creative commons attribution...

**Comment by zanzendegi** [comment]
Hi Navid, Thank you for the PR.

I am afraid to say this PR cannot be merged.

- We want the website to be static, assume there is no backend, no SSR, no `fetch`.
- Let keep the project pure Astro. Svelte is a great project an initially I voted for Svelte. But then we decided to go with Astro. So let's not mix them up.

The backend address `PUBLIC_BACK_API=http://127.0.0.1:4000` does not even exist. This a go-live repo in production (sorry no tests here). Anything merged here is publishes to fordem.org automatically.

**Comment by armantorkzaban** [comment]
The 'read from an API' has been my idea.

**Pull request closed without merging**
